apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloudnorth
data:
  DB_HOST: "cloudnorth-db-endpoint"  # replace with real RDS or in-cluster DB if needed later
  DB_NAME: "cloudnorth"